### ISSUE TITLE
Can't dup Fixnum

### ISSUE THREAD

**Issue by tfe** [shuber/sortable#1]
Installed the plugin and tried updating some foreign keys on records that are sortable... got the "can't dup fixnum" error, and the stack trace indicated line 372 of lib/sortable.rb which is:

```
        new_values = sortable_scope_changes.inject({}) { |hash, scope| value = send(scope); hash[scope] = value.nil? ? nil : value.dup; hash }
```

So value in that case is a Fixnum which can't be dup'd... but why wouldn't it be a Fixnum?  I'm not certain of what's going on in this block of code, but it seems like value would not necessarily always be dupable... am I right?

**Comment by shuber** [comment]
I think this has been fixed already. You may just need to update the gem.
